apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-petclinic
  name: spring-petclinic
spec:
  ports:
  - name: 3001-tcp
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: spring-petclinic
  sessionAffinity: None
  type: ClusterIP
